import Head from "next/head";
import Header from "./PageLayout/Header/Header";
import styles from "../styles/PageLayout.module.css"

const PageLayout = ({title, children}) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Header />
      <main className={styles.main}>
        {children}
      </main>

    </>
  );
};

export default PageLayout;
